export const GET_WEATHER = "GET_WEATHER";
export const GET_WEATHER_FAIL = "GET_WEATHER_FAIL";
export const GET_LOCATION = "GET_LOCATION";
export const GET_LOCATION_FAIL = "GET_LOCATION_FAIL";
export const CLEAR_STATE = "CLEAR_STATE";
export const SET_CURRENT = "SET_CURRENT";
export const SET_CURRENT_FAIL = "SET_CURRENT_FAIL";
export const GET_FORECAST = "GET_FORECAST";
export const GET_FORECAST_FAIL = "GET_FORECAST_FAIL";
export const USE_MY_GEO_POSITION = "USE_MY_GEO_POSITION";
export const USE_MY_GEO_POSITION_FAIL = "USE_MY_GEO_POSITION_FAIL";
export const GET_DAILY_FORECAST = "GET_DAILY_FORECAST";
export const GET_DAILY_FORECAST_FAIL = "GET_DAILY_FORECAST_FAIL";
export const GET_HOURLY_FORECAST = "GET_HOURLY_FORECAST";
export const GET_HOURLY_FORECAST_FAIL = "GET_HOURLY_FORECAST_FAIL";

export const REMOVE_ALERT = "REMOVE_ALERT";
export const SET_ALERT = "SET_ALERT";

// AUTH CONTEXT
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// WEATHER CONTEXT
export const SAVED_WEATHER_SUCCESS = "SAVED_WEATHER_SUCCESS";
export const GET_ALL_WEATHER_SUCCESS = "GET_ALL_WEATHER_SUCCESS";
export const GET_WEATHER_BY_ID_SUCCESS = "GET_WEATHER_BY_ID_SUCCESS";
export const DELETE_WEATHER_SUCCESS = "DELETE_WEATHER_SUCCESS";
export const SAVED_WEATHER_ERROR = "SAVED_WEATHER_ERROR";
export const GET_WEATHER_BY_ID_ERROR = "GET_WEATHER_BY_ID_ERROR";
export const GET_ALL_WEATHER_ERROR = "GET_ALL_WEATHER_ERROR";
export const DELETE_WEATHER_ERROR = "DELETE_WEATHER_ERROR";
